# Generated by Django 5.1.2 on 2024-11-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSignup',
            new_name='NewsletterSubscriber',
        ),
    ]
